### ISSUE TITLE
toc localization issue

### ISSUE THREAD

**Issue by ticianaciminari** [dotnet/docs.fr-fr#101]
@Youssef1313 commented on [Tue Jan 21 2020](https://github.com/dotnet/docs/issues/16767)

![image](https://user-images.githubusercontent.com/31348972/72786648-c5a44880-3c36-11ea-8b85-c2eeb173a84d.png)

static keyword shouldn't be localized in the toc.
I see the other keywords aren't localized in there is no special thing done for them.

cc: @JasonCard 

---

@BillWagner commented on [Tue Jan 21 2020](https://github.com/dotnet/docs/issues/16767#issuecomment-576715587)

/cc @DuncanmaMSFT Does the toc yaml syntax support non-localized keywords?

---

@JasonCard commented on [Tue Jan 21 2020](https://github.com/dotnet/docs/issues/16767#issuecomment-576805955)

I checked with @bodhigautam and unfortunately the [no-loc feature](https://review.docs.microsoft.com/en-us/help/contribute/markdown-reference?branch=master#non-localized-strings) does not work on yml files.
Our loc vendor will follow up on this issue.

@DavidPrio Could you please help to follow up on this issue?
Live: https://docs.microsoft.com/fr-fr/dotnet/csharp/language-reference/keywords/static 
Loc repo: https://github.com/dotnet/docs.fr-fr/blob/live/docs/csharp/toc.yml
Reported issue is that "static" is over-localized as "statique" in fr-fr, but it looks like there more keywords that are over-localized (e.g. "événement"). 
It's also over-localized for [es-es](https://docs.microsoft.com/es-es/dotnet/csharp/language-reference/keywords/static), [it-it](https://docs.microsoft.com/it-it/dotnet/csharp/language-reference/keywords/static), [ko-kr](https://docs.microsoft.com/ko-kr/dotnet/csharp/language-reference/keywords/static), [zh-cn](https://docs.microsoft.com/zh-cn/dotnet/csharp/language-reference/keywords/static), and [zh-tw](https://docs.microsoft.com/zh-cn/dotnet/csharp/language-reference/keywords/static).
Could you please help to have this entire TOC.yml reviewed for over-localization of keywords in all languages?

**Comment by srvbpigh** [comment]
Hello, @ticianaciminari
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
Hello, @Youssef1313,

Thank you for your feedback. 

Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/fr-fr/dotnet/csharp/language-reference/keywords/static.  

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback. 

Kind regards, 

Microsoft DOCS International Team
