### ISSUE TITLE
Une clause join qui est suivie de into se traduit par l’appel de la méthode GroupJoin.

### ISSUE THREAD

**Issue by gtop79** [dotnet/docs.fr-fr#102]
Le texte ci-dessous semble avoir été copier-coller. Il me semble que la phrase 2 est fausse.
Une clause join qui n’est pas suivie de into se traduit par l’appel de la méthode Join. 
Une clause join qui n’est pas suivie de into se traduit par l’appel de la méthode GroupJoin.

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 7f64bda9-3763-e0a0-fbb9-22f6fd50beca
* Version Independent ID: d552325f-7578-efb3-3f6d-927169181391
* Content: [join, clause - Référence C#](https://docs.microsoft.com/fr-fr/dotnet/csharp/language-reference/keywords/join-clause#feedback)
* Content Source: [docs/csharp/language-reference/keywords/join-clause.md](https://github.com/dotnet/docs.fr-fr/blob/live/docs/csharp/language-reference/keywords/join-clause.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by srvbpigh** [comment]
Hello, @gtop79
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
Bonjour @gtop79,

Merci pour votre contribution. 

Les contributions relatives aux problèmes de traduction dans le contenu traduit automatiquement ne sont actuellement pas acceptées. 

Nous apprécions vos contributions et suggestions au contenu issu de la traduction humaine, qui sont utilisées pour effectuer l’apprentissage des moteurs de traduction automatique. Vos contributions amélioreront ainsi la qualité des traductions humaine et machine. 

Pour distinguer les rubriques traduites manuellement de celles traduites automatiquement, référez-vous à la valeur de métadonnées ms.translationtype qui figure dans l’en-tête de chaque fichier de contenu : "HT" fait référence à la traduction humaine et "MT" à la traduction machine. 

Un grand merci pour votre aide. 

L’équipe Microsoft DOCS Global Experience
