### ISSUE TITLE
Les exemples sont manquants...

### ISSUE THREAD

**Issue by babouaya** [dotnet/docs.fr-fr#103]
Tous les exemples sont vides !

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 1e8e455c-1162-d046-ed70-22dfe96cbbad
* Version Independent ID: 9448a018-a06c-0ae5-049b-c4c424d1df9a
* Content: [Propriétés d'interface - Guide de programmation C#](https://docs.microsoft.com/fr-fr/dotnet/csharp/programming-guide/classes-and-structs/interface-properties#feedback)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/interface-properties.md](https://github.com/dotnet/docs.fr-fr/blob/live/docs/csharp/programming-guide/classes-and-structs/interface-properties.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by srvbpigh** [comment]
Hello, @babouaya
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by V-vafune** [comment]
Bonjour, @babouaya , 

Nous vous remercions sincèrement pour votre commentaire et nous nous efforçons d’améliorer votre expérience dans docs.microsoft.com. Cependant, nous avons besoin de plus d’informations pour pouvoir répondre à vos commentaires. Pouvez-vous fournir des informations plus détaillées et clarifier votre commentaire ? 

Cordialement, 

L’équipe internationale Microsoft DOCS

**Comment by babouaya** [comment]
Sur la page https://docs.microsoft.com/fr-fr/dotnet/csharp/programming-guide/classes-and-structs/interface-properties
les cadres contenant le code des exemples étaient vides. Mais je constate aujourd'hui que c'est réparé... Peut être le commit 01cad359d741027732e268eba8314fd6e383af7f a-t-il corrigé le problème ?

**Comment by V-vafune** [comment]
Bonjour @babouaya ,  

Merci pour votre feedback. Nous sommes heureux d’apprendre que notre documentation répond à vos attentes.  

Dans une optique d’amélioration constante, nous vous encourageons à envoyer vos commentaires à Microsoft.  

Cordialement,  

L’équipe Microsoft DOCS International
