### ISSUE TITLE
erreur de traduction

### ISSUE THREAD

**Issue by fred076java** [dotnet/docs.fr-fr#106]
[.NET Framework se compose de l’heure courante (CLR)]

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: a71f8d03-061a-1424-d09d-abf2e55ef046
* Version Independent ID: ace64e6c-6362-a0e6-4a6e-8ab2d249cfc5
* Content: [Vue d’ensemble du .NET Framework](https://docs.microsoft.com/fr-fr/dotnet/framework/get-started/overview)
* Content Source: [docs/framework/get-started/overview.md](https://github.com/dotnet/docs.fr-fr/blob/live/docs/framework/get-started/overview.md)
* Product: **dotnet-framework**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by srvbpigh** [comment]
Hello, @fred076java
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Bonjour @fred076java 

Merci pour votre contribution.
Les contributions relatives aux problèmes de traduction dans le contenu traduit automatiquement ne sont actuellement pas acceptées.

Nous apprécions vos contributions et suggestions au contenu issu de la traduction humaine, qui sont utilisées pour effectuer l’apprentissage des moteurs de traduction automatique. Vos contributions amélioreront ainsi la qualité des traductions humaine et machine.

Pour distinguer les rubriques traduites manuellement de celles traduites automatiquement, référez-vous à la valeur de métadonnées ms.translationtype qui figure dans l’en-tête de chaque fichier de contenu : "HT" fait référence à la traduction humaine et "MT" à la traduction machine.
Un grand merci pour votre aide.

L’équipe Microsoft DOCS Global Experience
