### ISSUE TITLE
Elsa workflow

### ISSUE THREAD

**Issue by Alexplose** [dotnet/docs.fr-fr#123]
Elsa workflow should be referenced as an alternative to Workflow Foundation, along with CoreWF.

[Elsa Workflow here](https://github.com/elsa-workflows/)

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: f8175dfa-c812-afef-c018-a5927995ef43
* Version Independent ID: 4fd72a98-c51f-cbd9-0578-d6448bab4749
* Content: [Nouveautés de .NET 5](https://docs.microsoft.com/fr-fr/dotnet/core/dotnet-five)
* Content Source: [docs/core/dotnet-five.md](https://github.com/dotnet/docs.fr-fr/blob/live/docs/core/dotnet-five.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi @Alexplose - please feel free to add a pull request adding it (reference this issue number), and we will review it. Thanks
