### ISSUE TITLE
How to update code snippets? 

### ISSUE THREAD

**Issue by spywen** [dotnet/docs.fr-fr#40]
Hello,
Thanks for this documentation, really interesting ;)
I just would like to know how to see code snippets.
For example i see: [!code-cscsProgGuideCodingConventions#7]
But:
- i'm not able to click on it: ok...
- by inspecting the code behind the file doesn't exist... : /dotnet/docs.fr-fr/blob/master/docs/csharp/programming-guide/inside-a-program/codesnippet/CSharp/coding-conventions_5.cs

Do not answer me: go on https://docs.microsoft.com/fr-fr/dotnet/csharp/programming-guide/inside-a-program/coding-conventions#commenting-conventions
-> I just would like to be able to participate and propose some fix on Github if possible :)

Thanks for your time ;)

**Comment by mairaw** [comment]
Hi @spywen,

All the sample code actually live in the English repo only.

So if you click and get an URL like this:
https://github.com/dotnet/docs.fr-fr/blob/live/docs/csharp/programming-guide/inside-a-program/codesnippet/CSharp/coding-conventions_1.cs

Remove the ".fr-fr" from the link and change that URL to:
https://github.com/dotnet/docs.fr-fr/blob/live/docs/csharp/programming-guide/inside-a-program/codesnippet/CSharp/coding-conventions_1.cs

Or you can go to the English version of the topic and click Edit and the links to the samples will work:
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/inside-a-program/coding-conventions#commenting-conventions

Thanks for your interest in contributing to our docs!

**Comment by spywen** [comment]
Thanks 👍
