### ISSUE TITLE
My successful solution for 0x800f081f error using Windows10.

### ISSUE THREAD

**Issue by nobarth** [dotnet/docs.fr-fr#60]
I tried several ways to solve 0x800f081f error using Windows10.

The only one that works was the following:

1) Mount your win10.iso
2) Copy  Win10MountDrive:\sources\SxS\microsoft-windows-netfx3-ondemand-package.cab to c:\temp\microsoft-windows-netfx3-ondemand-package.cab
3) Open an console as Administrator
4) Execute the following command:
&gt;dism /online /add-package /packagepath:c:\temp\microsoft-windows-netfx3-ondemand-package.cab

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: ea654e23-2ec5-637e-99c3-8870b895030c
* Version Independent ID: 9c054590-c5e3-199c-b852-e1a856b4aae7
* Content: [Installer le .NET Framework 3.5 sur Windows 10, Windows 8.1 et Windows 8](https://docs.microsoft.com/fr-fr/dotnet/framework/install/dotnet-35-windows-10)
* Content Source: [docs/framework/install/dotnet-35-windows-10.md](https://github.com/dotnet/docs.fr-fr/blob/live/docs/framework/install/dotnet-35-windows-10.md)
* GitHub Login: @rlander
* Microsoft Alias: **mairaw**

**Comment by gosali** [comment]
Hello, @nobarth , 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation. 

Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page. 

If you have any feedback related to the documentation, please feel free to log it through this channel. 

We truly appreciate your contribution to our articles.  
@nokura 
Kind regards, 
Microsoft DOCS International Team

**Comment by JonathanP91** [comment]
Hello,
Thank you for your work around, it help me install Framework 3.5 on windows 10 !
