### ISSUE TITLE
parole

### ISSUE THREAD

**Issue by bassyiene24mimoun** [dotnet/docs.fr-fr#61]
utilisation de Visual n est pas facile pour moi. et je me sent d une grande influence de Visual et office en général . si c est possible de le rendre plus facile a utilisé . parfois je vous adore autre fois je vous insulte. pour ceux qui ignore ce fils historique il est sous un grand fardeau nommé la parole donc ses insultes sont excusées n est ce pas messieurs ?  

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 9a3d410a-eed7-b86f-1707-6a5b1343f736
* Version Independent ID: 69c9300f-a523-f1bb-e6c4-28dfe457ba8f
* Content: [Ce que'nouveauté dans ADO.NET](https://docs.microsoft.com/fr-fr/dotnet/framework/data/adonet/whats-new#adonet-entity-framework)
* Content Source: [docs/framework/data/adonet/whats-new.md](https://github.com/dotnet/docs.fr-fr/blob/live/docs/framework/data/adonet/whats-new.md)
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by LisandroSu** [comment]
Bonjour

Merci pour votre contribution.   Notre équipe peut uniquement répondre au feedback qui porte sur la   documentation.
 
Pour envoyer vos commentaires   produit, nous vous invitons à cliquer sur le bouton « Envoyer   des commentaires sur le produit » situé au bas de la page Docs.

Si vous avez des commentaires   sur la documentation, n’hésitez pas à nous les envoyer via ce canal.
 
Votre contribution à nos   articles est grandement appréciée.

Cordialement,
L’équipe Microsoft DOCS   International
