### ISSUE TITLE
{Binding Source={StaticResource MyPhotos}}

### ISSUE THREAD

**Issue by O4D** [dotnet/docs.fr-fr#67]
Hello,

Can you tell me where do you define MyPhotos and how ?
If I use ItemsSource="{Binding Source={StaticResource MyPhotos}}" XAML seems to search into the &lt;resources&gt; something called MyPhotos.

And if I write only {Binding MyPhotos} in my XAML and create a List&lt;Photo&gt; in my .cs, the link isn't automaticaly done (MainWindow).

Thanks in advance

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 9dfc55ee-0061-cd98-fd01-ad6156f8d155
* Version Independent ID: 594e424a-30ed-9f1e-dac7-e56acdd022e0
* Content: [Application d'un style et création de modèles](https://docs.microsoft.com/fr-fr/dotnet/framework/wpf/controls/styling-and-templating)
* Content Source: [docs/framework/wpf/controls/styling-and-templating.md](https://github.com/dotnet/docs.fr-fr/blob/live/docs/framework/wpf/controls/styling-and-templating.md)
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by LisandroSu** [comment]
Hello, @O4D 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
