### ISSUE TITLE
Many BackgroundServices as HostedService

### ISSUE THREAD

**Issue by Helfics** [dotnet/docs.fr-fr#70]
Hi,
According to the documentation, we can declare many HostedServices based:
&lt;&lt;
    services.AddSingleton&lt;IHostedService, GracePeriodManagerService&gt;();
    services.AddSingleton&lt;IHostedService, MyHostedServiceB&gt;();
    services.AddSingleton&lt;IHostedService, MyHostedServiceC&gt;();
&gt;&gt;

Based on this documentation, I implemented two differents background services:
- SmallTimerBackgroundService, triggered each 3 seconds
- TinyTimerBackgroundService, triggered each second

I'm trying to do the same, but in my case, only the first subscription (instruction "services.AddSingleton") is working, the second one is just ignored.
If I switch the order, first one is working too, the others are ignored too.

Am I using it well?

You can find my code in my repo: https://github.com/Helfics/WithManyBackgroundServices/tree/develop

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: d49a03c0-a844-26eb-48a5-33a612dd3ead
* Version Independent ID: 45b409c8-f64d-da19-a2ec-b91f21696a5b
* Content: [Implémenter des tâches en arrière-plan dans les microservices avec IHostedService et la classe BackgroundService](https://docs.microsoft.com/fr-fr/dotnet/standard/microservices-architecture/multi-container-microservice-net-applications/background-tasks-with-ihostedservice#feedback)
* Content Source: [docs/standard/microservices-architecture/multi-container-microservice-net-applications/background-tasks-with-ihostedservice.md](https://github.com/dotnet/docs.fr-fr/blob/live/docs/standard/microservices-architecture/multi-container-microservice-net-applications/background-tasks-with-ihostedservice.md)
* GitHub Login: @CESARDELATORRE
* Microsoft Alias: **wiwagn**

**Comment by LisandroSu** [comment]
Hello, @Helfics 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
