### ISSUE TITLE
MenuScrollButton

### ISSUE THREAD

**Issue by frank4466** [dotnet/docs.fr-fr#82]
ou sont ces ressources : MenuScrollButton, UpArrow et DownArrow.

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 7c51dc5a-f211-6041-191b-e301d24f9b88
* Version Independent ID: 66edb7f3-bcd5-a631-1b8b-9d193845de25
* Content: [Styles et modèles Menu](https://docs.microsoft.com/fr-fr/dotnet/framework/wpf/controls/menu-styles-and-templates#feedback)
* Content Source: [docs/framework/wpf/controls/menu-styles-and-templates.md](https://github.com/dotnet/docs.fr-fr/blob/live/docs/framework/wpf/controls/menu-styles-and-templates.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Bonjour @frank4466 

Merci pour votre contribution. Notre équipe peut uniquement répondre au feedback qui porte sur la documentation. 

Pour envoyer vos commentaires produit, nous vous invitons à cliquer sur le bouton « Envoyer des commentaires sur le produit » situé au bas de la page Docs. 

Si vous avez des commentaires sur la documentation, n’hésitez pas à nous les envoyer via ce canal. 

Votre contribution à nos articles est grandement appréciée.  

Cordialement, 
L’équipe Microsoft DOCS International

**Comment by frank4466** [comment]
Bonjour et merci de votre réponse.
MAIS il s'agit bien de la documentation dont je parle. Quand on copie les code proposées il signale une erreur indiquant qu'il manque les styles MenuScrollButton, UpArrow et DownArrow. Pour les flèches c'est assez évident mais le Style MenuScrollButton est sans doute plus complexe et même si j'en ai reconstitué un c'est celui de l'exemple que je voulais voir.
