### ISSUE TITLE
Erreur de traduction

### ISSUE THREAD

**Issue by Ceber** [dotnet/docs.fr-fr#83]
Second paragraphe :
" [...] La première différence entre les types référence et les types valeur que nous considérerons est que les types référence sont alloués sur la pile et récupérés par le récupérateur de mémoire [...]".

qui correspond dans sa version anglaise à :
"[...] The first difference between reference types and value types we will consider is that reference types are allocated on the heap and garbage-collected [...]"

Les types référence sont alloués sur le tas, ce qui donnerait plutôt cette traduction :
" [...] La première différence entre les types référence et les types valeur que nous considérerons est que les types référence sont alloués sur le tas et récupérés par le récupérateur de mémoire [...]".
 

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 1e73f528-b4e2-cc81-3f49-faa9fbd9b153
* Version Independent ID: 66f0cfec-c8f1-2411-84d5-9e8cb09d7ff5
* Content: [Choix entre classe et structure](https://docs.microsoft.com/fr-fr/dotnet/standard/design-guidelines/choosing-between-class-and-struct#feedback)
* Content Source: [docs/standard/design-guidelines/choosing-between-class-and-struct.md](https://github.com/dotnet/docs.fr-fr/blob/live/docs/standard/design-guidelines/choosing-between-class-and-struct.md)
* Product: **dotnet**
* GitHub Login: @KrzysztofCwalina
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Bonjour, @Ceber 

Merci pour votre feedback. 

Nous révisons activement vos commentaires et nous vous recontacterons bientôt. 

Cordialement, 
L’équipe Microsoft DOCS International

**Comment by Ceber** [comment]
Bonjour @CeciAc,

Merci pour votre réponse.
Cette phrase est importante à corriger car elle induit en erreur sur l'allocation "mémoire" des types "référence".

**Comment by CeciAc** [comment]
Bonjour @Ceber 

Merci pour votre feedback. 

Notre équipe linguistique a examiné vos suggestions de traduction et les a acceptées. Nous avons modifié les articles concernés selon vos suggestions et les avons republiés sur les pages https://docs.microsoft.com/fr-fr/dotnet/standard/design-guidelines/choosing-between-class-and-struct du site Docs.  

Votre contribution à nos articles est grandement appréciée. Nous vous encourageons donc à continuer d’envoyer vos commentaires à Microsoft. 

Cordialement, 
L’équipe Microsoft DOCS International
