### ISSUE TITLE
Faute d'orthographe "boule Parallel.ForEach"

### ISSUE THREAD

**Issue by v-stein** [dotnet/docs.fr-fr#85]
Après le bloc de code du paragraphe "Exemple" figure "Une boule Parallel.ForEach" au lieu de "Une boucle Parallel.ForEach"

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 25dcc671-50d5-032b-735c-2ac9b6a21338
* Version Independent ID: c70450e1-1006-7478-fcca-45c8bfbe2c09
* Content: [Écrire un programme parallèle simple à l’aide de Parallel.ForEach](https://docs.microsoft.com/fr-fr/dotnet/standard/parallel-programming/how-to-write-a-simple-parallel-foreach-loop#feedback)
* Content Source: [docs/standard/parallel-programming/how-to-write-a-simple-parallel-foreach-loop.md](https://github.com/dotnet/docs.fr-fr/blob/live/docs/standard/parallel-programming/how-to-write-a-simple-parallel-foreach-loop.md)
* Product: **dotnet**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by CeciAc** [comment]
Bonjour, @v-stein 

Merci pour votre feedback. 

Nous révisons activement vos commentaires et nous vous recontacterons bientôt. 

Cordialement, 
L’équipe Microsoft DOCS International

**Comment by CeciAc** [comment]
Bonjour @v-stein 

Merci pour votre feedback. 

Notre équipe linguistique a examiné vos suggestions de traduction et les a acceptées. Nous avons modifié les articles concernés selon vos suggestions et les avons republiés sur les pages https://docs.microsoft.com/fr-fr/dotnet/standard/parallel-programming/how-to-write-a-simple-parallel-foreach-loop du site Docs.  

Votre contribution à nos articles est grandement appréciée. Nous vous encourageons donc à continuer d’envoyer vos commentaires à Microsoft. 

Cordialement, 
L’équipe Microsoft DOCS International
