### ISSUE TITLE
Performances en mémoire

### ISSUE THREAD

**Issue by jmhoubre** [dotnet/docs.fr-fr#90]
Le choix des différentes manières d'utiliser les chaînes a-t-il des incidences sur l'utilisation de la mémoire ?

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 88a5e33e-938d-b72d-b211-ab5245413af5
* Version Independent ID: db96afbb-50af-5dee-b7b3-97600161e737
* Content: [Procédure : Concaténer plusieurs chaînes (Guide C#)](https://docs.microsoft.com/fr-fr/dotnet/csharp/how-to/concatenate-multiple-strings#feedback)
* Content Source: [docs/csharp/how-to/concatenate-multiple-strings.md](https://github.com/dotnet/docs.fr-fr/blob/live/docs/csharp/how-to/concatenate-multiple-strings.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by CeciAc** [comment]
Bonjour @jmhoubre 

Merci pour votre contribution. Notre équipe peut uniquement répondre au feedback qui porte sur la documentation. 

Pour envoyer vos commentaires produit, nous vous invitons à cliquer sur le bouton « Envoyer des commentaires sur le produit » situé au bas de la page Docs. 

Si vous avez des commentaires sur la documentation, n’hésitez pas à nous les envoyer via ce canal. 

Votre contribution à nos articles est grandement appréciée.  

Cordialement, 
L’équipe Microsoft DOCS International
