### ISSUE TITLE
Incorrect link target for "Default WPF Themes"

### ISSUE THREAD

**Issue by gdurand** [dotnet/docs.fr-fr#91]
The link https://go.microsoft.com/fwlink/?LinkID=158252 for "Default WPF Themes" redirects to https://github.com/microsoft/WPF-Samples/tree/master/Graphics/2DTransforms which does not seem to be the proper content.

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 6821e183-9eb7-a22c-faa4-a4d19cdf10c5
* Version Independent ID: 234cafe7-028d-bb80-d0a2-0874cfda7c3c
* Content: [Personnalisation de l'apparence d'un contrôle existant en créant un ControlTemplate](https://docs.microsoft.com/fr-fr/dotnet/framework/wpf/controls/customizing-the-appearance-of-an-existing-control?view=netframework-4.8)
* Content Source: [docs/framework/wpf/controls/customizing-the-appearance-of-an-existing-control.md](https://github.com/dotnet/docs.fr-fr/blob/live/docs/framework/wpf/controls/customizing-the-appearance-of-an-existing-control.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Hello, @gdurand

Your contribution is much appreciated. Your feedback is related to the original documentation.https://github.com/dotnet/docs/issues/13216XXX.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
