### ISSUE TITLE
Author

### ISSUE THREAD

**Issue by Gbosshard** [dotnet/docs.fr-fr#97]
Try :
[Author("ST ...", version = 29.7)]  

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 5deee0dd-859f-1dc5-4cc1-b9366cf5220f
* Version Independent ID: 72041048-d399-cc42-a7f9-7ed4c9a0fbd0
* Content: [Création d’attributs personnalisés (C#)](https://docs.microsoft.com/fr-fr/dotnet/csharp/programming-guide/concepts/attributes/creating-custom-attributes#feedback)
* Content Source: [docs/csharp/programming-guide/concepts/attributes/creating-custom-attributes.md](https://github.com/dotnet/docs.fr-fr/blob/live/docs/csharp/programming-guide/concepts/attributes/creating-custom-attributes.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by srvbpigh** [comment]
Hello, @Gbosshard
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @Gbosshard 
 
We truly appreciate your comment and we strive to improve your experience in docs.microsoft.com. However, we need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment?
 
Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @Gbosshard 
 
We are following up on our previous comment. We need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment?
 
Kind regards,
Microsoft DOCS International Team

**Comment by Gbosshard** [comment]
The exemple of Author Name in this page is Kock and Ackerman
Kock is a deformation of Cock or French Rooster (Cock), remainder of INPI
installation in france (IMPI side (the INPI is the stabilisation old IMPIE
crisis about property right)) : economic right and sex authorisation in
this case is in a bad state but sometime and for many folks it's suffisant
(I think that the owner lived in Arbois (village where I have spend my
youth))

Ackerman is a dutch family name who has made deposit of many "Marque" or
"Brand" I don't know exactely like Cartier or maybe Rolex for discoverer of
this setting approach (old legend speak about Eli Prophet has been the last
owner of first deposit) (and other legend say that it's Rividel a French
Land Pirate who has find this Idee (Washington and "Traité de Vienne" in
france (excuse me wikipedia as remove the info, I speak about the Banque de
France partage between Messersmith, Rothschild,...))). after Hacker is the
defense of Author right

I depose my "Marque" on INPI system : "AdidOs" with good standard (Marque
de Bon Produit), so Economic Right and ... is possible to. you can see on
INPI system more info
ST ... is I think a good name on comment for author right under the
protection of this
Scientifique, Saint is enought Hard to evite false deposit and ... let
installation replace the wanter

for the version number, reference to printing and A4 (order fort) is I
think the best on exemple (remember that paper is a stronger component for
information stockage (exemple : write EARTH on a circle on A4 and tacks it
on the ceilling (maybe add "0Ring 1MOON")))

Have a good day

Le ven. 11 oct. 2019 à 21:36, Cecilia Acevedo <notifications@github.com> a
écrit :

**Comment by CeciAc** [comment]
Hello, @Gbosshard 

Your comments are in violation of our code of conduct on https://opensource.microsoft.com/codeofconduct/. 
For this reason, we have to lock and close this issue.

Kind regards,
Microsoft DOCS International Team
